import { Theme, ThemeSpacing, ThemeTypography, ThemeBorderRadius, ThemeFonts } from './types';

const spacing: ThemeSpacing = {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
};

const typography: ThemeTypography = {
    sizes: {
        caption: 11,
        footnote: 13,
        body: 15,
        callout: 16,
        headline: 17,
        title3: 20,
        title2: 22,
        title1: 26,
    },
    weights: {
        regular: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
    },
    lineHeights: {
        tight: 1.2,
        normal: 1.4,
        relaxed: 1.6,
    },
    letterSpacing: {
        tight: -0.4,
        normal: 0,
        wide: 0.4,
    },
};

const borderRadius: ThemeBorderRadius = {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 22,
    pill: 999,
};

const fonts: ThemeFonts = {
    regular: 'PlusJakartaSans_400Regular',
    medium: 'PlusJakartaSans_500Medium',
    semibold: 'PlusJakartaSans_600SemiBold',
    bold: 'PlusJakartaSans_700Bold',
};

export const lightTheme: Theme = {
    id: 'light',
    name: 'Light',
    colors: {
        background: '#E8EEFF',
        surface: '#FFFFFF',
        surfaceSecondary: '#F0F0F2',
        textPrimary: '#1A1A2E',
        textSecondary: '#6B6B80',
        textTertiary: '#9D9DB0',
        textInverse: '#FFFFFF',
        primary: '#6366F1',
        primaryMuted: '#E0E7FF',
        accent: '#8B5CF6',
        border: '#E2E2F0',
        borderLight: '#F0F0F8',
        success: '#34C759',
        successMuted: '#E8F8ED',
        danger: '#EF4444',
        dangerMuted: '#FEE2E2',
        warning: '#F59E0B',
        warningMuted: '#FEF3C7',
        calendarToday: '#D1FAE5',
        calendarOfficeDay: '#E0E7FF',
        calendarTimeOff: '#FEF3C7',
        calendarSelected: '#6366F1',
        overlay: 'rgba(0, 0, 0, 0.4)',
        disabled: '#C7C7D0',
        disabledText: '#8E8E9D',
    },
    spacing,
    typography,
    borderRadius,
    shadow: {
        none: {
            shadowColor: 'transparent',
            shadowOffset: { width: 0, height: 0 },
            shadowOpacity: 0,
            shadowRadius: 0,
            elevation: 0,
        },
        sm: {
            shadowColor: '#6366F1',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.06,
            shadowRadius: 3,
            elevation: 1,
        },
        md: {
            shadowColor: '#6366F1',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.08,
            shadowRadius: 6,
            elevation: 2,
        },
        lg: {
            shadowColor: '#6366F1',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.12,
            shadowRadius: 12,
            elevation: 4,
        },
    },
    gradient: {
        colors: ['#E0E7FF', '#FCE7F3'],
        start: { x: 0, y: 0 },
        end: { x: 1, y: 1 },
    },
    glass: {
        surface: {
            background: 'rgba(255, 255, 255, 0.7)',
            borderColor: 'rgba(255, 255, 255, 0.5)',
            borderWidth: 1,
        },
        surfaceSecondary: {
            background: 'rgba(255, 255, 255, 0.45)',
            borderColor: 'rgba(255, 255, 255, 0.35)',
            borderWidth: 1,
        },
        modal: {
            background: 'rgba(255, 255, 255, 0.85)',
            borderColor: 'rgba(255, 255, 255, 0.6)',
            borderWidth: 1,
        },
    },
    fonts,
    statusBarStyle: 'dark',
};

export const darkTheme: Theme = {
    id: 'dark',
    name: 'Dark',
    colors: {
        background: '#0F0B2E',
        surface: '#1C1840',
        surfaceSecondary: '#262050',
        textPrimary: '#EAEAFF',
        textSecondary: '#A0A0C0',
        textTertiary: '#6B6B90',
        textInverse: '#1A1A2E',
        primary: '#818CF8',
        primaryMuted: '#1E1B4B',
        accent: '#A78BFA',
        border: '#2E2860',
        borderLight: '#222050',
        success: '#34D399',
        successMuted: '#1A3A2E',
        danger: '#F87171',
        dangerMuted: '#3A1A1E',
        warning: '#FBBF24',
        warningMuted: '#3A3A1A',
        calendarToday: '#064E3B',
        calendarOfficeDay: '#1E1B4B',
        calendarTimeOff: '#3A3A1A',
        calendarSelected: '#818CF8',
        overlay: 'rgba(0, 0, 0, 0.6)',
        disabled: '#3A3A50',
        disabledText: '#6B6B90',
    },
    spacing,
    typography,
    borderRadius,
    shadow: {
        none: {
            shadowColor: 'transparent',
            shadowOffset: { width: 0, height: 0 },
            shadowOpacity: 0,
            shadowRadius: 0,
            elevation: 0,
        },
        sm: {
            shadowColor: '#818CF8',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.15,
            shadowRadius: 3,
            elevation: 1,
        },
        md: {
            shadowColor: '#818CF8',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.2,
            shadowRadius: 6,
            elevation: 2,
        },
        lg: {
            shadowColor: '#818CF8',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.3,
            shadowRadius: 12,
            elevation: 4,
        },
    },
    gradient: {
        colors: ['#0F0B2E', '#1E1338'],
        start: { x: 0, y: 0 },
        end: { x: 1, y: 1 },
    },
    glass: {
        surface: {
            background: 'rgba(255, 255, 255, 0.08)',
            borderColor: 'rgba(255, 255, 255, 0.12)',
            borderWidth: 1,
        },
        surfaceSecondary: {
            background: 'rgba(255, 255, 255, 0.04)',
            borderColor: 'rgba(255, 255, 255, 0.08)',
            borderWidth: 1,
        },
        modal: {
            background: 'rgba(30, 25, 60, 0.92)',
            borderColor: 'rgba(255, 255, 255, 0.15)',
            borderWidth: 1,
        },
    },
    fonts,
    statusBarStyle: 'light',
};

export const sandTheme: Theme = {
    id: 'sand',
    name: 'Sand',
    colors: {
        background: '#FEF3E2',
        surface: '#FFFBF5',
        surfaceSecondary: '#F5EDE0',
        textPrimary: '#2C2420',
        textSecondary: '#7A6E60',
        textTertiary: '#A69888',
        textInverse: '#FFFBF5',
        primary: '#EA580C',
        primaryMuted: '#FED7AA',
        accent: '#D97706',
        border: '#E8DDD0',
        borderLight: '#F0E8DC',
        success: '#65A30D',
        successMuted: '#ECFCCB',
        danger: '#DC2626',
        dangerMuted: '#FEE2E2',
        warning: '#CA8A04',
        warningMuted: '#FEF9C3',
        calendarToday: '#D9F99D',
        calendarOfficeDay: '#FED7AA',
        calendarTimeOff: '#FEF9C3',
        calendarSelected: '#EA580C',
        overlay: 'rgba(44, 36, 32, 0.4)',
        disabled: '#C7C0B0',
        disabledText: '#A69888',
    },
    spacing,
    typography,
    borderRadius,
    shadow: {
        none: {
            shadowColor: 'transparent',
            shadowOffset: { width: 0, height: 0 },
            shadowOpacity: 0,
            shadowRadius: 0,
            elevation: 0,
        },
        sm: {
            shadowColor: '#EA580C',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.06,
            shadowRadius: 3,
            elevation: 1,
        },
        md: {
            shadowColor: '#EA580C',
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.08,
            shadowRadius: 6,
            elevation: 2,
        },
        lg: {
            shadowColor: '#EA580C',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.12,
            shadowRadius: 12,
            elevation: 4,
        },
    },
    gradient: {
        colors: ['#FEF3E2', '#FECDD3'],
        start: { x: 0, y: 0 },
        end: { x: 1, y: 1 },
    },
    glass: {
        surface: {
            background: 'rgba(255, 255, 255, 0.65)',
            borderColor: 'rgba(255, 255, 255, 0.45)',
            borderWidth: 1,
        },
        surfaceSecondary: {
            background: 'rgba(255, 255, 255, 0.4)',
            borderColor: 'rgba(255, 255, 255, 0.3)',
            borderWidth: 1,
        },
        modal: {
            background: 'rgba(255, 251, 245, 0.88)',
            borderColor: 'rgba(255, 255, 255, 0.55)',
            borderWidth: 1,
        },
    },
    fonts,
    statusBarStyle: 'dark',
};

export const themes: Record<string, Theme> = {
    light: lightTheme,
    dark: darkTheme,
    sand: sandTheme,
};
